services:
  pilot-bot:
    container_name: pilot-bot
    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped


    env_file:
      - .env.production
    environment:
      NODE_ENV: production
      PORT: 3200
      TZ: Europe/Samara

    ports:
      - "127.0.0.1:3200:3200"

    volumes:
      - ./data:/app/data